name: Build

on: [push, pull_request]

# doing as cibuildwheel docs says leads to frankenstein arm builds on macos
# so lets be more explicit, no linux arm build as not available on github

jobs:
  build_wheels:
    name: Wheel ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
        - [ubuntu-latest, manylinux_x86_64, auto]
        - [macos-13, macosx_x86_64, x86_64]
        - [macos-14, macosx_arm64, arm64]
        python: ["cp38", "cp39", "cp310", "cp311", "cp312"]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          CIBW_ARCHS: ${{ matrix.buildplat[2] }}
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.python }}-${{ matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl


  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build sdist
        run: python setup.py sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist
